### PR TITLE
Mimeparse should gracefully handle an invalid mime type of the form "text/extra/part"

### PR DESCRIPTION
**Pull request by wojcikstefan**
Hi @dbtsai. See the added test data to understand the use case. Could you merge + make a release?

### CODE REVIEW

**Comment by dbtsai** [comment]
Thanks.

**Comment by wojcikstefan** [comment]
Thanks for merging @dbtsai. Let me know if you could make a new PyPI release :)

**Comment by dbtsai** [comment]
@wojcikstefan Since I'm not actively on this project anymore, how about I add you as new maintainer?

**Comment by wojcikstefan** [comment]
I'd be happy/honored to share the responsibility :)

**Comment by dbtsai** [comment]
@wojcikstefan Do you have the PyPI account?

**Comment by wojcikstefan** [comment]
@dbtsai Yup, my username on PyPI is wojcikstefan (same as GitHub).

**Comment by dbtsai** [comment]
@wojcikstefan I just added you as owner. Feel free to make a new release. Thanks.

**Comment by wojcikstefan** [comment]
@dbtsai I tried to push a new commit to master (to bump `__version__` to `1.5.2`), but got:

```
(venv)[python-mimeparse] g pus
ERROR: Permission to dbtsai/python-mimeparse.git denied to wojcikstefan.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dbtsai** [comment]
@wojcikstefan I add you permission this repo. Please try it again. Thanks.

**Pull request merged**
